# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mcx_tracking_cam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mcx_tracking_cam.proto',
  package='mcx_tracking_cam',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16mcx_tracking_cam.proto\x12\x10mcx_tracking_cam\"\x85\x01\n\x04\x42lob\x12\x0c\n\x04type\x18\x01 \x02(\r\x12\x0f\n\x07padding\x18\x02 \x02(\r\x12\n\n\x02\x63x\x18\x03 \x02(\r\x12\n\n\x02\x63y\x18\x04 \x02(\r\x12\x0c\n\x04\x61rea\x18\x05 \x02(\r\x12\x0c\n\x04left\x18\x06 \x02(\r\x12\r\n\x05right\x18\x07 \x02(\r\x12\x0b\n\x03top\x18\x08 \x02(\r\x12\x0e\n\x06\x62ottom\x18\t \x02(\r\".\n\x05\x42lobs\x12%\n\x05value\x18\x01 \x03(\x0b\x32\x16.mcx_tracking_cam.Blob\"8\n\x06Marker\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07rotVec3\x18\x02 \x03(\x01\x12\x11\n\ttransVec3\x18\x03 \x03(\x01\"2\n\x07Markers\x12\'\n\x05value\x18\x01 \x03(\x0b\x32\x18.mcx_tracking_cam.Marker\"9\n\x06Pose2D\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x01\x12\t\n\x01y\x18\x03 \x02(\x01\x12\r\n\x05\x61ngle\x18\x04 \x02(\x01\"`\n\nProjection\x12(\n\x06origin\x18\x01 \x02(\x0b\x32\x18.mcx_tracking_cam.Marker\x12(\n\x06points\x18\x02 \x03(\x0b\x32\x18.mcx_tracking_cam.Pose2D\"B\n\x04Line\x12\n\n\x02id\x18\x01 \x02(\r\x12\n\n\x02x0\x18\x02 \x02(\x01\x12\n\n\x02y0\x18\x03 \x02(\x01\x12\n\n\x02x1\x18\x04 \x02(\x01\x12\n\n\x02y1\x18\x05 \x02(\x01\".\n\x05Lines\x12%\n\x05value\x18\x01 \x03(\x0b\x32\x16.mcx_tracking_cam.Line\"5\n\x06\x43ircle\x12\n\n\x02id\x18\x01 \x02(\r\x12\t\n\x01r\x18\x02 \x02(\x01\x12\t\n\x01x\x18\x03 \x02(\x01\x12\t\n\x01y\x18\x04 \x02(\x01\"2\n\x07\x43ircles\x12\'\n\x05value\x18\x01 \x03(\x0b\x32\x18.mcx_tracking_cam.Circle\">\n\x04Sign\x12\n\n\x02id\x18\x01 \x02(\r\x12\t\n\x01x\x18\x02 \x02(\x01\x12\t\n\x01y\x18\x03 \x02(\x01\x12\t\n\x01w\x18\x04 \x02(\x01\x12\t\n\x01h\x18\x05 \x02(\x01\".\n\x05Signs\x12%\n\x05value\x18\x01 \x03(\x0b\x32\x16.mcx_tracking_cam.Sign'
)




_BLOB = _descriptor.Descriptor(
  name='Blob',
  full_name='mcx_tracking_cam.Blob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mcx_tracking_cam.Blob.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding', full_name='mcx_tracking_cam.Blob.padding', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cx', full_name='mcx_tracking_cam.Blob.cx', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cy', full_name='mcx_tracking_cam.Blob.cy', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='area', full_name='mcx_tracking_cam.Blob.area', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left', full_name='mcx_tracking_cam.Blob.left', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='mcx_tracking_cam.Blob.right', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top', full_name='mcx_tracking_cam.Blob.top', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='mcx_tracking_cam.Blob.bottom', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=178,
)


_BLOBS = _descriptor.Descriptor(
  name='Blobs',
  full_name='mcx_tracking_cam.Blobs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Blobs.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=226,
)


_MARKER = _descriptor.Descriptor(
  name='Marker',
  full_name='mcx_tracking_cam.Marker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Marker.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotVec3', full_name='mcx_tracking_cam.Marker.rotVec3', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transVec3', full_name='mcx_tracking_cam.Marker.transVec3', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=284,
)


_MARKERS = _descriptor.Descriptor(
  name='Markers',
  full_name='mcx_tracking_cam.Markers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Markers.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=336,
)


_POSE2D = _descriptor.Descriptor(
  name='Pose2D',
  full_name='mcx_tracking_cam.Pose2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Pose2D.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='mcx_tracking_cam.Pose2D.x', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mcx_tracking_cam.Pose2D.y', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='mcx_tracking_cam.Pose2D.angle', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=395,
)


_PROJECTION = _descriptor.Descriptor(
  name='Projection',
  full_name='mcx_tracking_cam.Projection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin', full_name='mcx_tracking_cam.Projection.origin', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points', full_name='mcx_tracking_cam.Projection.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=493,
)


_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='mcx_tracking_cam.Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Line.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x0', full_name='mcx_tracking_cam.Line.x0', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y0', full_name='mcx_tracking_cam.Line.y0', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x1', full_name='mcx_tracking_cam.Line.x1', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y1', full_name='mcx_tracking_cam.Line.y1', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=561,
)


_LINES = _descriptor.Descriptor(
  name='Lines',
  full_name='mcx_tracking_cam.Lines',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Lines.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=609,
)


_CIRCLE = _descriptor.Descriptor(
  name='Circle',
  full_name='mcx_tracking_cam.Circle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Circle.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r', full_name='mcx_tracking_cam.Circle.r', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='mcx_tracking_cam.Circle.x', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mcx_tracking_cam.Circle.y', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=664,
)


_CIRCLES = _descriptor.Descriptor(
  name='Circles',
  full_name='mcx_tracking_cam.Circles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Circles.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=666,
  serialized_end=716,
)


_SIGN = _descriptor.Descriptor(
  name='Sign',
  full_name='mcx_tracking_cam.Sign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mcx_tracking_cam.Sign.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='mcx_tracking_cam.Sign.x', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mcx_tracking_cam.Sign.y', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='mcx_tracking_cam.Sign.w', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='mcx_tracking_cam.Sign.h', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=780,
)


_SIGNS = _descriptor.Descriptor(
  name='Signs',
  full_name='mcx_tracking_cam.Signs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mcx_tracking_cam.Signs.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=782,
  serialized_end=828,
)

_BLOBS.fields_by_name['value'].message_type = _BLOB
_MARKERS.fields_by_name['value'].message_type = _MARKER
_PROJECTION.fields_by_name['origin'].message_type = _MARKER
_PROJECTION.fields_by_name['points'].message_type = _POSE2D
_LINES.fields_by_name['value'].message_type = _LINE
_CIRCLES.fields_by_name['value'].message_type = _CIRCLE
_SIGNS.fields_by_name['value'].message_type = _SIGN
DESCRIPTOR.message_types_by_name['Blob'] = _BLOB
DESCRIPTOR.message_types_by_name['Blobs'] = _BLOBS
DESCRIPTOR.message_types_by_name['Marker'] = _MARKER
DESCRIPTOR.message_types_by_name['Markers'] = _MARKERS
DESCRIPTOR.message_types_by_name['Pose2D'] = _POSE2D
DESCRIPTOR.message_types_by_name['Projection'] = _PROJECTION
DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['Lines'] = _LINES
DESCRIPTOR.message_types_by_name['Circle'] = _CIRCLE
DESCRIPTOR.message_types_by_name['Circles'] = _CIRCLES
DESCRIPTOR.message_types_by_name['Sign'] = _SIGN
DESCRIPTOR.message_types_by_name['Signs'] = _SIGNS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blob = _reflection.GeneratedProtocolMessageType('Blob', (_message.Message,), {
  'DESCRIPTOR' : _BLOB,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Blob)
  })
_sym_db.RegisterMessage(Blob)

Blobs = _reflection.GeneratedProtocolMessageType('Blobs', (_message.Message,), {
  'DESCRIPTOR' : _BLOBS,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Blobs)
  })
_sym_db.RegisterMessage(Blobs)

Marker = _reflection.GeneratedProtocolMessageType('Marker', (_message.Message,), {
  'DESCRIPTOR' : _MARKER,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Marker)
  })
_sym_db.RegisterMessage(Marker)

Markers = _reflection.GeneratedProtocolMessageType('Markers', (_message.Message,), {
  'DESCRIPTOR' : _MARKERS,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Markers)
  })
_sym_db.RegisterMessage(Markers)

Pose2D = _reflection.GeneratedProtocolMessageType('Pose2D', (_message.Message,), {
  'DESCRIPTOR' : _POSE2D,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Pose2D)
  })
_sym_db.RegisterMessage(Pose2D)

Projection = _reflection.GeneratedProtocolMessageType('Projection', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTION,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Projection)
  })
_sym_db.RegisterMessage(Projection)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), {
  'DESCRIPTOR' : _LINE,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Line)
  })
_sym_db.RegisterMessage(Line)

Lines = _reflection.GeneratedProtocolMessageType('Lines', (_message.Message,), {
  'DESCRIPTOR' : _LINES,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Lines)
  })
_sym_db.RegisterMessage(Lines)

Circle = _reflection.GeneratedProtocolMessageType('Circle', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLE,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Circle)
  })
_sym_db.RegisterMessage(Circle)

Circles = _reflection.GeneratedProtocolMessageType('Circles', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLES,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Circles)
  })
_sym_db.RegisterMessage(Circles)

Sign = _reflection.GeneratedProtocolMessageType('Sign', (_message.Message,), {
  'DESCRIPTOR' : _SIGN,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Sign)
  })
_sym_db.RegisterMessage(Sign)

Signs = _reflection.GeneratedProtocolMessageType('Signs', (_message.Message,), {
  'DESCRIPTOR' : _SIGNS,
  '__module__' : 'mcx_tracking_cam_pb2'
  # @@protoc_insertion_point(class_scope:mcx_tracking_cam.Signs)
  })
_sym_db.RegisterMessage(Signs)


# @@protoc_insertion_point(module_scope)
